#! /usr/bin/env bash
if [[ $VIRTUAL_ENV ]];
then
    pip install sphinx sphinxcontrib-bibtex sphinxcontrib-proof \
        sphinx-autobuild sphinxcontrib-youtube \
        sphinxcontrib-blockdiag sphinx-reredirects
    pip install git+https://github.com/dham/sphinxcontrib-details-directive.git
else
    echo ERROR: please activate the finite element course venv
    exit 1
fi
