#!/usr/bin/env python
import os
import github  # Install pygithub
import git     # Install gitpython
from argparse import ArgumentParser
import subprocess
import sys

parser = ArgumentParser(
    description="""Helper script to mark finite element assignments.""")
parser.add_argument(
    "--update", action="store_true", help="Update all student repositories.")
parser.add_argument(
    "--push-masters", action="store_true",
    help="Push the master branch of all student repos to the instructor repo.")
parser.add_argument("--checkout", type=str, action="store", metavar=("REPO"),
                    help="checkout finite-element/fe-%d-REPO." % 0)
parser.add_argument("--test", action="store_true", help="Execute tests")
parser.add_argument("-x", action="store_true", help="Stop on first test fail")
parser.add_argument("--week", type=str, action="store", required=True,
                    help="Week whose repositories should be cloned.")
args = parser.parse_args()

repo = git.Repo(".")

if args.update:
    g = github.Github(os.environ["GITHUB_OAUTH"])
    org = g.get_organization("Imperial-MATH50009")
    count = 0

    for r in org.get_repos():
        if r.name.startswith("exercises-week-%s" % args.week):
            count += 1
            uname = r.name[10:]
            print("Looking for remote %s" % uname)
            try:
                remote = repo.remote(uname)
                print("Found")
            except ValueError:
                print("Not found. Creating")
                remote = repo.create_remote(uname, r.ssh_url)
            print("Fetching")
            remote.fetch()
    print(f"{count} repos found.")

if args.push_masters:
    g = github.Github(os.environ["GITHUB_OAUTH"])
    org = g.get_organization("finite-element")

    remote = repo.remote(instructor)

    for r in org.get_repos():
        if r.name.startswith("fe-%d" % year):
            uname = r.name[8:]
            print("Pushing master for remote %s" % uname)
            remote.push("remotes/{0}/master:refs/heads/{0}-master".format(uname))


if args.checkout:
    user = args.checkout
    print("Checking out head for %s" % user)
    head = repo.create_head(user, commit="/%s/implementation" % user)
    repo.head.reference = head
    repo.head.reset(working_tree=True)
    print("success")

if args.test:
    os.environ["PYTHONPATH"] = repo.working_tree_dir
    test_args = ["-x"] if args.x else []
    try:
        subprocess.check_output(["py.test"] + test_args)
    except subprocess.CalledProcessError as e:
        sys.stdout.write(e.output.decode("utf8"))
